# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
print(A)

[[0.46221403 0.68091993 0.56161864 0.03307146 0.60477936 0.16372932
  0.44395394 0.48206891 0.40779959 0.13110894]
 [0.79206158 0.64137115 0.03464327 0.78773019 0.62245651 0.43207948
  0.44801144 0.87964774 0.60589952 0.43005652]
 [0.86933044 0.5762707  0.37706682 0.82805767 0.39264606 0.32837199
  0.39251027 0.472809   0.339064   0.70413227]
 [0.75177969 0.50217932 0.4330504  0.46364456 0.03976297 0.15242594
  0.99473519 0.22990336 0.05181378 0.06780096]
 [0.69048778 0.89630442 0.28561482 0.77866807 0.51659388 0.25582341
  0.80881963 0.73122847 0.71499417 0.52914614]
 [0.50712754 0.33809243 0.17000779 0.45665167 0.46951552 0.72263972
  0.35164372 0.51914664 0.79269735 0.9969942 ]
 [0.03251441 0.12043508 0.60598045 0.7395635  0.35336861 0.34352221
  0.43112113 0.68430169 0.25380337 0.33532061]
 [0.14140892 0.06688472 0.95374815 0.38049047 0.21169477 0.61430175
  0.36135326 0.19472126 0.08281877 0.41418097]
 [0.38086212 0.46399423 0.0344205  0.59303907 0.78871574 0.2126492
  0.11643796 

In [5]:
#3.3: return only the odd rows of A
A[::2]

array([[0.46221403, 0.68091993, 0.56161864, 0.03307146, 0.60477936,
        0.16372932, 0.44395394, 0.48206891, 0.40779959, 0.13110894],
       [0.86933044, 0.5762707 , 0.37706682, 0.82805767, 0.39264606,
        0.32837199, 0.39251027, 0.472809  , 0.339064  , 0.70413227],
       [0.69048778, 0.89630442, 0.28561482, 0.77866807, 0.51659388,
        0.25582341, 0.80881963, 0.73122847, 0.71499417, 0.52914614],
       [0.03251441, 0.12043508, 0.60598045, 0.7395635 , 0.35336861,
        0.34352221, 0.43112113, 0.68430169, 0.25380337, 0.33532061],
       [0.38086212, 0.46399423, 0.0344205 , 0.59303907, 0.78871574,
        0.2126492 , 0.11643796, 0.23243057, 0.10313937, 0.97719502]])

In [8]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A, A.T)

array([[1.99934394, 2.2219421 , 1.95736332, 1.57943885, 2.54246538,
        1.83782221, 1.40052126, 1.23010784, 1.37666235, 1.64985716],
       [2.2219421 , 3.76113954, 3.20981325, 2.09681798, 3.84350218,
        3.11188307, 2.16802992, 1.44634285, 2.38979234, 2.63629842],
       [1.95736332, 3.20981325, 3.16606064, 2.12026794, 3.43431684,
        2.85385235, 2.0050463 , 1.6746301 , 2.36068862, 2.21315979],
       [1.57943885, 2.09681798, 2.12026794, 2.29430575, 2.55904289,
        1.54301133, 1.37871122, 1.26797386, 1.11383311, 1.40635383],
       [2.54246538, 3.84350218, 3.43431684, 2.55904289, 4.2804462 ,
        3.24311369, 2.35775951, 1.70581612, 2.46727886, 2.91445203],
       [1.83782221, 3.11188307, 2.85385235, 1.54301133, 3.24311369,
        3.36710428, 1.95446221, 1.68027736, 2.36829197, 2.65504017],
       [1.40052126, 2.16802992, 2.0050463 , 1.37871122, 2.35775951,
        1.95446221, 2.00359545, 1.60677348, 1.44257224, 1.81534697],
       [1.23010784, 1.44634285, 1.6746301

In [11]:
#3.5: compute the matrix inverse of A
inverse = np.linalg.inv(A)
inverse

array([[ 9.53559235e-01,  4.40225613e-01,  2.00920265e+00,
         9.77574776e-01, -3.09279288e+00, -2.47571916e-01,
        -1.64688552e-01, -9.77030928e-01, -6.50289029e-02,
         1.17655290e+00],
       [-1.19606396e+00, -4.53309563e-01, -1.86999368e+00,
        -2.01257731e+00,  6.09105212e+00,  8.31462526e-01,
        -1.07619137e+00,  1.80222315e+00, -8.99584197e-01,
        -3.37432551e+00],
       [ 8.80711151e-01, -8.62681228e-01,  1.44522837e+00,
        -2.37121063e-01, -7.74015510e-01, -5.03815287e-01,
         3.57987223e-01,  8.37938946e-02, -2.99845120e-01,
         5.85174837e-01],
       [-1.17555331e+00,  1.35816633e+00,  7.03957455e-01,
        -2.11579012e-01, -5.32006334e-01, -2.68358306e+00,
        -1.17294354e+00,  1.39203498e+00,  7.97392942e-01,
         2.08448962e+00],
       [ 1.04535001e+00,  1.91875756e+00,  4.82746206e-03,
         1.08693535e+00, -4.07313954e+00, -2.58161152e+00,
        -9.84398782e-01,  3.59827801e-01,  2.15994726e+00,
         3.

In [15]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A <= 0.5, A, A/2)

array([[0.46221403, 0.34045997, 0.28080932, 0.03307146, 0.30238968,
        0.16372932, 0.44395394, 0.48206891, 0.40779959, 0.13110894],
       [0.39603079, 0.32068557, 0.03464327, 0.3938651 , 0.31122826,
        0.43207948, 0.44801144, 0.43982387, 0.30294976, 0.43005652],
       [0.43466522, 0.28813535, 0.37706682, 0.41402884, 0.39264606,
        0.32837199, 0.39251027, 0.472809  , 0.339064  , 0.35206614],
       [0.37588984, 0.25108966, 0.4330504 , 0.46364456, 0.03976297,
        0.15242594, 0.49736759, 0.22990336, 0.05181378, 0.06780096],
       [0.34524389, 0.44815221, 0.28561482, 0.38933404, 0.25829694,
        0.25582341, 0.40440981, 0.36561424, 0.35749708, 0.26457307],
       [0.25356377, 0.33809243, 0.17000779, 0.45665167, 0.46951552,
        0.36131986, 0.35164372, 0.25957332, 0.39634867, 0.4984971 ],
       [0.03251441, 0.12043508, 0.30299023, 0.36978175, 0.35336861,
        0.34352221, 0.43112113, 0.34215085, 0.25380337, 0.33532061],
       [0.14140892, 0.06688472, 0.4768740

In [16]:
#print the matrix A to test the assignment 3.6
A

array([[0.46221403, 0.68091993, 0.56161864, 0.03307146, 0.60477936,
        0.16372932, 0.44395394, 0.48206891, 0.40779959, 0.13110894],
       [0.79206158, 0.64137115, 0.03464327, 0.78773019, 0.62245651,
        0.43207948, 0.44801144, 0.87964774, 0.60589952, 0.43005652],
       [0.86933044, 0.5762707 , 0.37706682, 0.82805767, 0.39264606,
        0.32837199, 0.39251027, 0.472809  , 0.339064  , 0.70413227],
       [0.75177969, 0.50217932, 0.4330504 , 0.46364456, 0.03976297,
        0.15242594, 0.99473519, 0.22990336, 0.05181378, 0.06780096],
       [0.69048778, 0.89630442, 0.28561482, 0.77866807, 0.51659388,
        0.25582341, 0.80881963, 0.73122847, 0.71499417, 0.52914614],
       [0.50712754, 0.33809243, 0.17000779, 0.45665167, 0.46951552,
        0.72263972, 0.35164372, 0.51914664, 0.79269735, 0.9969942 ],
       [0.03251441, 0.12043508, 0.60598045, 0.7395635 , 0.35336861,
        0.34352221, 0.43112113, 0.68430169, 0.25380337, 0.33532061],
       [0.14140892, 0.06688472, 0.9537481